[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86-64"

[[project]]
path = ""
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86-64"

[project.opts]
compiler = "nasm"
diagnostics = true
default_diagnostics = true
compile_flags_txt = [
    "-f",
    "elf64",
    "-o",
    "bin/main.o"
]
